// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mgr-x-msg-ne.proto

#ifndef PROTOBUF_mgr_2dx_2dmsg_2dne_2eproto__INCLUDED
#define PROTOBUF_mgr_2dx_2dmsg_2dne_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_mgr_2dx_2dmsg_2dne_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsXmsgImMgrNeNetLoadReq_ExtEntry_DoNotUseImpl();
void InitDefaultsXmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse();
void InitDefaultsXmsgImMgrNeNetLoadReqImpl();
void InitDefaultsXmsgImMgrNeNetLoadReq();
void InitDefaultsXmsgImMgrNeNetLoadRsp_KvEntry_DoNotUseImpl();
void InitDefaultsXmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse();
void InitDefaultsXmsgImMgrNeNetLoadRspImpl();
void InitDefaultsXmsgImMgrNeNetLoadRsp();
inline void InitDefaults() {
  InitDefaultsXmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse();
  InitDefaultsXmsgImMgrNeNetLoadReq();
  InitDefaultsXmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse();
  InitDefaultsXmsgImMgrNeNetLoadRsp();
}
}  // namespace protobuf_mgr_2dx_2dmsg_2dne_2eproto
class XmsgImMgrNeNetLoadReq;
class XmsgImMgrNeNetLoadReqDefaultTypeInternal;
extern XmsgImMgrNeNetLoadReqDefaultTypeInternal _XmsgImMgrNeNetLoadReq_default_instance_;
class XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse;
class XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUseDefaultTypeInternal;
extern XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUseDefaultTypeInternal _XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse_default_instance_;
class XmsgImMgrNeNetLoadRsp;
class XmsgImMgrNeNetLoadRspDefaultTypeInternal;
extern XmsgImMgrNeNetLoadRspDefaultTypeInternal _XmsgImMgrNeNetLoadRsp_default_instance_;
class XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse;
class XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUseDefaultTypeInternal;
extern XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUseDefaultTypeInternal _XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse_default_instance_;

// ===================================================================

class XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse();
  XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse& other);
  static const XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse*>(&_XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class XmsgImMgrNeNetLoadReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImMgrNeNetLoadReq) */ {
 public:
  XmsgImMgrNeNetLoadReq();
  virtual ~XmsgImMgrNeNetLoadReq();

  XmsgImMgrNeNetLoadReq(const XmsgImMgrNeNetLoadReq& from);

  inline XmsgImMgrNeNetLoadReq& operator=(const XmsgImMgrNeNetLoadReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImMgrNeNetLoadReq(XmsgImMgrNeNetLoadReq&& from) noexcept
    : XmsgImMgrNeNetLoadReq() {
    *this = ::std::move(from);
  }

  inline XmsgImMgrNeNetLoadReq& operator=(XmsgImMgrNeNetLoadReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImMgrNeNetLoadReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImMgrNeNetLoadReq* internal_default_instance() {
    return reinterpret_cast<const XmsgImMgrNeNetLoadReq*>(
               &_XmsgImMgrNeNetLoadReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(XmsgImMgrNeNetLoadReq* other);
  friend void swap(XmsgImMgrNeNetLoadReq& a, XmsgImMgrNeNetLoadReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImMgrNeNetLoadReq* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImMgrNeNetLoadReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImMgrNeNetLoadReq& from);
  void MergeFrom(const XmsgImMgrNeNetLoadReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImMgrNeNetLoadReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> ext = 1;
  int ext_size() const;
  void clear_ext();
  static const int kExtFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      ext() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_ext();

  // @@protoc_insertion_point(class_scope:XmsgImMgrNeNetLoadReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > ext_;
  mutable int _cached_size_;
  friend struct ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::TableStruct;
  friend void ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::InitDefaultsXmsgImMgrNeNetLoadReqImpl();
};
// -------------------------------------------------------------------

class XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse();
  XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse& other);
  static const XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse*>(&_XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class XmsgImMgrNeNetLoadRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XmsgImMgrNeNetLoadRsp) */ {
 public:
  XmsgImMgrNeNetLoadRsp();
  virtual ~XmsgImMgrNeNetLoadRsp();

  XmsgImMgrNeNetLoadRsp(const XmsgImMgrNeNetLoadRsp& from);

  inline XmsgImMgrNeNetLoadRsp& operator=(const XmsgImMgrNeNetLoadRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XmsgImMgrNeNetLoadRsp(XmsgImMgrNeNetLoadRsp&& from) noexcept
    : XmsgImMgrNeNetLoadRsp() {
    *this = ::std::move(from);
  }

  inline XmsgImMgrNeNetLoadRsp& operator=(XmsgImMgrNeNetLoadRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XmsgImMgrNeNetLoadRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XmsgImMgrNeNetLoadRsp* internal_default_instance() {
    return reinterpret_cast<const XmsgImMgrNeNetLoadRsp*>(
               &_XmsgImMgrNeNetLoadRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(XmsgImMgrNeNetLoadRsp* other);
  friend void swap(XmsgImMgrNeNetLoadRsp& a, XmsgImMgrNeNetLoadRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XmsgImMgrNeNetLoadRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  XmsgImMgrNeNetLoadRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XmsgImMgrNeNetLoadRsp& from);
  void MergeFrom(const XmsgImMgrNeNetLoadRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XmsgImMgrNeNetLoadRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> kv = 1;
  int kv_size() const;
  void clear_kv();
  static const int kKvFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      kv() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_kv();

  // @@protoc_insertion_point(class_scope:XmsgImMgrNeNetLoadRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > kv_;
  mutable int _cached_size_;
  friend struct ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::TableStruct;
  friend void ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::InitDefaultsXmsgImMgrNeNetLoadRspImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// XmsgImMgrNeNetLoadReq

// map<string, string> ext = 1;
inline int XmsgImMgrNeNetLoadReq::ext_size() const {
  return ext_.size();
}
inline void XmsgImMgrNeNetLoadReq::clear_ext() {
  ext_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
XmsgImMgrNeNetLoadReq::ext() const {
  // @@protoc_insertion_point(field_map:XmsgImMgrNeNetLoadReq.ext)
  return ext_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
XmsgImMgrNeNetLoadReq::mutable_ext() {
  // @@protoc_insertion_point(field_mutable_map:XmsgImMgrNeNetLoadReq.ext)
  return ext_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// XmsgImMgrNeNetLoadRsp

// map<string, string> kv = 1;
inline int XmsgImMgrNeNetLoadRsp::kv_size() const {
  return kv_.size();
}
inline void XmsgImMgrNeNetLoadRsp::clear_kv() {
  kv_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
XmsgImMgrNeNetLoadRsp::kv() const {
  // @@protoc_insertion_point(field_map:XmsgImMgrNeNetLoadRsp.kv)
  return kv_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
XmsgImMgrNeNetLoadRsp::mutable_kv() {
  // @@protoc_insertion_point(field_mutable_map:XmsgImMgrNeNetLoadRsp.kv)
  return kv_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mgr_2dx_2dmsg_2dne_2eproto__INCLUDED
