// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mgr-x-msg-ne.proto

#include "mgr-x-msg-ne.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse>
      _instance;
} _XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse_default_instance_;
class XmsgImMgrNeNetLoadReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<XmsgImMgrNeNetLoadReq>
      _instance;
} _XmsgImMgrNeNetLoadReq_default_instance_;
class XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse>
      _instance;
} _XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse_default_instance_;
class XmsgImMgrNeNetLoadRspDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<XmsgImMgrNeNetLoadRsp>
      _instance;
} _XmsgImMgrNeNetLoadRsp_default_instance_;
namespace protobuf_mgr_2dx_2dmsg_2dne_2eproto {
void InitDefaultsXmsgImMgrNeNetLoadReq_ExtEntry_DoNotUseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse_default_instance_;
    new (ptr) ::XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse();
  }
  ::XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse::InitAsDefaultInstance();
}

void InitDefaultsXmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsXmsgImMgrNeNetLoadReq_ExtEntry_DoNotUseImpl);
}

void InitDefaultsXmsgImMgrNeNetLoadReqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_mgr_2dx_2dmsg_2dne_2eproto::InitDefaultsXmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse();
  {
    void* ptr = &::_XmsgImMgrNeNetLoadReq_default_instance_;
    new (ptr) ::XmsgImMgrNeNetLoadReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::XmsgImMgrNeNetLoadReq::InitAsDefaultInstance();
}

void InitDefaultsXmsgImMgrNeNetLoadReq() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsXmsgImMgrNeNetLoadReqImpl);
}

void InitDefaultsXmsgImMgrNeNetLoadRsp_KvEntry_DoNotUseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse_default_instance_;
    new (ptr) ::XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse();
  }
  ::XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse::InitAsDefaultInstance();
}

void InitDefaultsXmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsXmsgImMgrNeNetLoadRsp_KvEntry_DoNotUseImpl);
}

void InitDefaultsXmsgImMgrNeNetLoadRspImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_mgr_2dx_2dmsg_2dne_2eproto::InitDefaultsXmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse();
  {
    void* ptr = &::_XmsgImMgrNeNetLoadRsp_default_instance_;
    new (ptr) ::XmsgImMgrNeNetLoadRsp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::XmsgImMgrNeNetLoadRsp::InitAsDefaultInstance();
}

void InitDefaultsXmsgImMgrNeNetLoadRsp() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsXmsgImMgrNeNetLoadRspImpl);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadReq, ext_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::XmsgImMgrNeNetLoadRsp, kv_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse)},
  { 9, -1, sizeof(::XmsgImMgrNeNetLoadReq)},
  { 15, 22, sizeof(::XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse)},
  { 24, -1, sizeof(::XmsgImMgrNeNetLoadRsp)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_XmsgImMgrNeNetLoadReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_XmsgImMgrNeNetLoadRsp_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "mgr-x-msg-ne.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022mgr-x-msg-ne.proto\"q\n\025XmsgImMgrNeNetLo"
      "adReq\022,\n\003ext\030\001 \003(\0132\037.XmsgImMgrNeNetLoadR"
      "eq.ExtEntry\032*\n\010ExtEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005"
      "value\030\002 \001(\t:\0028\001\"n\n\025XmsgImMgrNeNetLoadRsp"
      "\022*\n\002kv\030\001 \003(\0132\036.XmsgImMgrNeNetLoadRsp.KvE"
      "ntry\032)\n\007KvEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 "
      "\001(\t:\0028\001B\027\n\010x.msg.pbB\013XmsgNeMgrPbb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 280);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mgr-x-msg-ne.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_mgr_2dx_2dmsg_2dne_2eproto

// ===================================================================

XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse::XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse() {}
XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse::XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse::MergeFrom(const XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse::GetMetadata() const {
  ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::file_level_metadata[0];
}
void XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void XmsgImMgrNeNetLoadReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int XmsgImMgrNeNetLoadReq::kExtFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

XmsgImMgrNeNetLoadReq::XmsgImMgrNeNetLoadReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::InitDefaultsXmsgImMgrNeNetLoadReq();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:XmsgImMgrNeNetLoadReq)
}
XmsgImMgrNeNetLoadReq::XmsgImMgrNeNetLoadReq(const XmsgImMgrNeNetLoadReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ext_.MergeFrom(from.ext_);
  // @@protoc_insertion_point(copy_constructor:XmsgImMgrNeNetLoadReq)
}

void XmsgImMgrNeNetLoadReq::SharedCtor() {
  _cached_size_ = 0;
}

XmsgImMgrNeNetLoadReq::~XmsgImMgrNeNetLoadReq() {
  // @@protoc_insertion_point(destructor:XmsgImMgrNeNetLoadReq)
  SharedDtor();
}

void XmsgImMgrNeNetLoadReq::SharedDtor() {
}

void XmsgImMgrNeNetLoadReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* XmsgImMgrNeNetLoadReq::descriptor() {
  ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const XmsgImMgrNeNetLoadReq& XmsgImMgrNeNetLoadReq::default_instance() {
  ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::InitDefaultsXmsgImMgrNeNetLoadReq();
  return *internal_default_instance();
}

XmsgImMgrNeNetLoadReq* XmsgImMgrNeNetLoadReq::New(::google::protobuf::Arena* arena) const {
  XmsgImMgrNeNetLoadReq* n = new XmsgImMgrNeNetLoadReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void XmsgImMgrNeNetLoadReq::Clear() {
// @@protoc_insertion_point(message_clear_start:XmsgImMgrNeNetLoadReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ext_.Clear();
  _internal_metadata_.Clear();
}

bool XmsgImMgrNeNetLoadReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:XmsgImMgrNeNetLoadReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<string, string> ext = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&ext_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "XmsgImMgrNeNetLoadReq.ExtEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "XmsgImMgrNeNetLoadReq.ExtEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:XmsgImMgrNeNetLoadReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:XmsgImMgrNeNetLoadReq)
  return false;
#undef DO_
}

void XmsgImMgrNeNetLoadReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:XmsgImMgrNeNetLoadReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, string> ext = 1;
  if (!this->ext().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "XmsgImMgrNeNetLoadReq.ExtEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "XmsgImMgrNeNetLoadReq.ExtEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->ext().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->ext().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->ext().begin();
          it != this->ext().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(ext_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->ext().begin();
          it != this->ext().end(); ++it) {
        entry.reset(ext_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:XmsgImMgrNeNetLoadReq)
}

::google::protobuf::uint8* XmsgImMgrNeNetLoadReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:XmsgImMgrNeNetLoadReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, string> ext = 1;
  if (!this->ext().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "XmsgImMgrNeNetLoadReq.ExtEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "XmsgImMgrNeNetLoadReq.ExtEntry.value");
      }
    };

    if (deterministic &&
        this->ext().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->ext().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->ext().begin();
          it != this->ext().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(ext_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->ext().begin();
          it != this->ext().end(); ++it) {
        entry.reset(ext_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:XmsgImMgrNeNetLoadReq)
  return target;
}

size_t XmsgImMgrNeNetLoadReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:XmsgImMgrNeNetLoadReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<string, string> ext = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->ext_size());
  {
    ::google::protobuf::scoped_ptr<XmsgImMgrNeNetLoadReq_ExtEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->ext().begin();
        it != this->ext().end(); ++it) {
      entry.reset(ext_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void XmsgImMgrNeNetLoadReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:XmsgImMgrNeNetLoadReq)
  GOOGLE_DCHECK_NE(&from, this);
  const XmsgImMgrNeNetLoadReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const XmsgImMgrNeNetLoadReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:XmsgImMgrNeNetLoadReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:XmsgImMgrNeNetLoadReq)
    MergeFrom(*source);
  }
}

void XmsgImMgrNeNetLoadReq::MergeFrom(const XmsgImMgrNeNetLoadReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:XmsgImMgrNeNetLoadReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  ext_.MergeFrom(from.ext_);
}

void XmsgImMgrNeNetLoadReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:XmsgImMgrNeNetLoadReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void XmsgImMgrNeNetLoadReq::CopyFrom(const XmsgImMgrNeNetLoadReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:XmsgImMgrNeNetLoadReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XmsgImMgrNeNetLoadReq::IsInitialized() const {
  return true;
}

void XmsgImMgrNeNetLoadReq::Swap(XmsgImMgrNeNetLoadReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void XmsgImMgrNeNetLoadReq::InternalSwap(XmsgImMgrNeNetLoadReq* other) {
  using std::swap;
  ext_.Swap(&other->ext_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata XmsgImMgrNeNetLoadReq::GetMetadata() const {
  protobuf_mgr_2dx_2dmsg_2dne_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse::XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse() {}
XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse::XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse::MergeFrom(const XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse::GetMetadata() const {
  ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::file_level_metadata[2];
}
void XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void XmsgImMgrNeNetLoadRsp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int XmsgImMgrNeNetLoadRsp::kKvFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

XmsgImMgrNeNetLoadRsp::XmsgImMgrNeNetLoadRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::InitDefaultsXmsgImMgrNeNetLoadRsp();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:XmsgImMgrNeNetLoadRsp)
}
XmsgImMgrNeNetLoadRsp::XmsgImMgrNeNetLoadRsp(const XmsgImMgrNeNetLoadRsp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  kv_.MergeFrom(from.kv_);
  // @@protoc_insertion_point(copy_constructor:XmsgImMgrNeNetLoadRsp)
}

void XmsgImMgrNeNetLoadRsp::SharedCtor() {
  _cached_size_ = 0;
}

XmsgImMgrNeNetLoadRsp::~XmsgImMgrNeNetLoadRsp() {
  // @@protoc_insertion_point(destructor:XmsgImMgrNeNetLoadRsp)
  SharedDtor();
}

void XmsgImMgrNeNetLoadRsp::SharedDtor() {
}

void XmsgImMgrNeNetLoadRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* XmsgImMgrNeNetLoadRsp::descriptor() {
  ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const XmsgImMgrNeNetLoadRsp& XmsgImMgrNeNetLoadRsp::default_instance() {
  ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::InitDefaultsXmsgImMgrNeNetLoadRsp();
  return *internal_default_instance();
}

XmsgImMgrNeNetLoadRsp* XmsgImMgrNeNetLoadRsp::New(::google::protobuf::Arena* arena) const {
  XmsgImMgrNeNetLoadRsp* n = new XmsgImMgrNeNetLoadRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void XmsgImMgrNeNetLoadRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:XmsgImMgrNeNetLoadRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  kv_.Clear();
  _internal_metadata_.Clear();
}

bool XmsgImMgrNeNetLoadRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:XmsgImMgrNeNetLoadRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<string, string> kv = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&kv_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "XmsgImMgrNeNetLoadRsp.KvEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "XmsgImMgrNeNetLoadRsp.KvEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:XmsgImMgrNeNetLoadRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:XmsgImMgrNeNetLoadRsp)
  return false;
#undef DO_
}

void XmsgImMgrNeNetLoadRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:XmsgImMgrNeNetLoadRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, string> kv = 1;
  if (!this->kv().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "XmsgImMgrNeNetLoadRsp.KvEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "XmsgImMgrNeNetLoadRsp.KvEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->kv().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->kv().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->kv().begin();
          it != this->kv().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(kv_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->kv().begin();
          it != this->kv().end(); ++it) {
        entry.reset(kv_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:XmsgImMgrNeNetLoadRsp)
}

::google::protobuf::uint8* XmsgImMgrNeNetLoadRsp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:XmsgImMgrNeNetLoadRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, string> kv = 1;
  if (!this->kv().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "XmsgImMgrNeNetLoadRsp.KvEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "XmsgImMgrNeNetLoadRsp.KvEntry.value");
      }
    };

    if (deterministic &&
        this->kv().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->kv().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->kv().begin();
          it != this->kv().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(kv_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->kv().begin();
          it != this->kv().end(); ++it) {
        entry.reset(kv_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:XmsgImMgrNeNetLoadRsp)
  return target;
}

size_t XmsgImMgrNeNetLoadRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:XmsgImMgrNeNetLoadRsp)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<string, string> kv = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->kv_size());
  {
    ::google::protobuf::scoped_ptr<XmsgImMgrNeNetLoadRsp_KvEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->kv().begin();
        it != this->kv().end(); ++it) {
      entry.reset(kv_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void XmsgImMgrNeNetLoadRsp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:XmsgImMgrNeNetLoadRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const XmsgImMgrNeNetLoadRsp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const XmsgImMgrNeNetLoadRsp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:XmsgImMgrNeNetLoadRsp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:XmsgImMgrNeNetLoadRsp)
    MergeFrom(*source);
  }
}

void XmsgImMgrNeNetLoadRsp::MergeFrom(const XmsgImMgrNeNetLoadRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:XmsgImMgrNeNetLoadRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  kv_.MergeFrom(from.kv_);
}

void XmsgImMgrNeNetLoadRsp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:XmsgImMgrNeNetLoadRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void XmsgImMgrNeNetLoadRsp::CopyFrom(const XmsgImMgrNeNetLoadRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:XmsgImMgrNeNetLoadRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XmsgImMgrNeNetLoadRsp::IsInitialized() const {
  return true;
}

void XmsgImMgrNeNetLoadRsp::Swap(XmsgImMgrNeNetLoadRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void XmsgImMgrNeNetLoadRsp::InternalSwap(XmsgImMgrNeNetLoadRsp* other) {
  using std::swap;
  kv_.Swap(&other->kv_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata XmsgImMgrNeNetLoadRsp::GetMetadata() const {
  protobuf_mgr_2dx_2dmsg_2dne_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mgr_2dx_2dmsg_2dne_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
